/*
 * Software License Agreement (MIT License)
 *
 * Copyright (c) 2017, DUKELEC, Inc.
 * All rights reserved.
 *
 * Author: Duke Fong <d@d-l.io>
 */

#ifndef __CD_CONFIG_H__
#define __CD_CONFIG_H__

//#define ARCH_SPI
#define CD_FRAME_SIZE       258

#define DEBUG
//#define VERBOSE
//#define LIST_DEBUG
#define DBG_STR_LEN         160

#define CD_LIST_IT
#define CD_IRQ_SAFE
#define CDN_IRQ_SAFE

#define CDUART_IDLE_TIME    (500000 / SYSTICK_US_DIV) // 500 ms

//#define CDN_L0_C

#include "main.h"  // generated by stm32cube
#include "debug_config.h"

#endif
