/*
 * Software License Agreement (MIT License)
 *
 * Copyright (c) 2017, DUKELEC, Inc.
 * All rights reserved.
 *
 * Author: Duke Fong <d@d-l.io>
 */

#ifndef __CD_CONFIG_H__
#define __CD_CONFIG_H__

//#define CDCTL_SYS_CLK       150000000UL // 150MHz for CDCTL01A
extern int CDCTL_SYS_CLK;

#define ARCH_SPI
#define ARCH_CRC_HW
#define CDUART_CRC          crc16_hw
#define CDUART_CRC_SUB      crc16_hw_sub
#define CRC_HW_IRQ_SAFE

#define CD_FRAME_SIZE       258

#define DEBUG
//#define VERBOSE
//#define LIST_DEBUG
#define DBG_STR_LEN         160

#define CD_LIST_IT
#define CD_IRQ_SAFE
#define CDN_IRQ_SAFE

//#define CDN_L0_C

#define CDUART_IDLE_TIME (100000 / SYSTICK_US_DIV) // 100 ms

#include "main.h"  // generated by stm32cube
#include "debug_config.h"

#endif
