/*
 * Software License Agreement (MIT License)
 *
 * Copyright (c) 2017, DUKELEC, Inc.
 * All rights reserved.
 *
 * Author: Duke Fong <d@d-l.io>
 */

#ifndef __CD_CONFIG_H__
#define __CD_CONFIG_H__

#define CDCTL_OSC_CLK       24000000UL // 24MHz

#define CD_ARCH_SPI
#define CD_ARCH_CRC_HW
#define CDUART_CRC          crc16_hw
#define CDUART_CRC_SUB      crc16_hw_sub
#define CRC_HW_IRQ_SAFE

#define CD_FRAME_SIZE       258

#define CD_DEBUG
//#define CD_VERBOSE
//#define CD_LIST_DEBUG
#define CD_DBG_STR_LEN      160

#define CD_LIST_IT
#define CD_IRQ_SAFE
#define CDN_IRQ_SAFE

//#define CDN_L0_C

#define CDUART_IDLE_TIME (100000 / CD_SYSTICK_US_DIV) // 100 ms

#include "main.h"  // generated by stm32cube
#include "debug_config.h"

#endif
